version: '3'
services:

  #
  # """  PHP Services  """
  #
  #

  # PHP 8
  php8:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: common_php8/latest
    container_name: 'php8_${APP_NAME}'
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: common_php8
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: 'nginx_${APP_NAME}'
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #Node Service
  node:
    image: node:alpine
    container_name: 'node_${APP_NAME}'
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www

  #MySQL Services
  mysql:
    image: mysql:5.7.22
    container_name: mysql_${APP_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  #Redis Service
  redis:
    image: "redis:alpine"
    container_name: common_redis
    restart: unless-stopped
    tty: true
    command: redis-server
    ports:
      - "6379:6379"
  composer:
    image: composer:latest
    container_name: 'composer_${APP_NAME}'
    volumes:
      - .:/var/www
#Volumes
volumes:
  dbdata:
    driver: local